SELECT
TRANSACTION_TOKEN,
TRANSACTION_DATE,
DROPOUT_REASON
from AP_CUR_XOOP_G.PAY_MONTHLY.M_ATM_ATTEMPT_MASTER
WHERE MERCHANT_COUNTRY = 'US'
AND TRANSACTION_DATE BETWEEN '2023-07-01' AND '2023-07-31'
AND DROPOUT_REASON IN (
'Invalid Payment details',
'Insufficient Funds',
'Risk - Fraud'
,'Payment error'
)
AND STATUS_REASON NOT IN ('CROSS_COUNTRY_CARD_REJECTION','TOPAZ_PURCHASE_ENQUIRE_REJECTION') --- additional declines with payment error
